---
- name: install mas cli with homebrew
  homebrew:
    name: mas
    state: present

- name: check mas is installed
  shell: brew list
  register: mas_brew_list
  changed_when: False
  check_mode: no

- name: Get MAS account status
  command: mas account
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  check_mode: false
  changed_when: false

- name: List installed MAS apps.
  command: mas list
  register: mas_installed_list
  check_mode: false
  changed_when: false

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item.id }}"
  with_items: "{{ mas_installed_apps }}"
  when: (item.id | string) not in mas_installed_list.stdout