---
settings:
  - { domain: NSGlobalDomain, key: AppleShowAllExtensions, type: bool, value: TRUE }
  - { domain: com.apple.menuextra.battery, key: ShowPercent, type: string, value: YES }
  - { domain: com.apple.menuextra.clock, key: DateFormat, type: string, value: "M\\U6708d\\U65e5(EEE)  H:mm" }
  - { domain: com.apple.dock, key: autohide, type: bool, value: TRUE }
  - { domain: com.apple.dock, key: autohide-delay, type: float, value: 0 }

  - { domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: TRUE }
  - { domain: com.apple.finder, key: _FXShowPosixPathInTitle, type: bool, value: TRUE }

  - { domain: com.apple.desktopservices, key: DSDontWriteNetworkStores, type: bool, value: TRUE }
  - { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: Clicking, type: bool, value: TRUE }
  - { domain: com.apple.screencapture, key: location, type: string, value: ~/Pictures/Screenshot }
  - { domain: com.apple.screencapture, key: name, type: string, value: "SS_" }
