---
- name: DNS setting
  command: networksetup -setdnsservers Wi-Fi 8.8.8.8 1.1.1.1 1.0.0.1 8.8.4.4 2606:4700:4700::1111 2606:4700:4700::1001

- name: set macOSX defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items: "{{ settings }}"

- name: reflect settings
  command: killall "{{item}}"
  with_items:
    - Dock
    - Finder
    - SystemUIServer